/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sig.view;

import java.util.ArrayList;
import sig.controller.ListOfListener;

import sig.controller.FileActions;
import sig.model.HeaderModel;
import sig.model.InoviceHeaderTable;
import sig.model.LineModel;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author chika family
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form invoiceFrame
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AllHeadersTbl = new javax.swing.JTable();
        CreateNewInvoiceBtn = new javax.swing.JButton();
        CreateNewInvoiceBtn.addActionListener(handler);
        DeleteInvoiceBtn = new javax.swing.JButton();
        DeleteInvoiceBtn.addActionListener(handler);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NumLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        CustomerLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AllLinesTbl = new javax.swing.JTable();
        javax.swing.JButton SaveLineBtn = new javax.swing.JButton();
        SaveLineBtn.addActionListener(handler);
        DeleteLineBtn = new javax.swing.JButton();
        DeleteLineBtn.addActionListener(handler);
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadMenuBtn = new javax.swing.JMenuItem();
        LoadMenuBtn.addActionListener(handler);
        SaveMenuBtn = new javax.swing.JMenuItem();
        SaveMenuBtn.addActionListener(handler);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AllHeadersTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        AllHeadersTbl.getSelectionModel().addListSelectionListener(selectionListener);
        jScrollPane1.setViewportView(AllHeadersTbl);

        CreateNewInvoiceBtn.setText("Create New Invoice");
        CreateNewInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewInvoiceBtnActionPerformed(evt);
            }
        });

        DeleteInvoiceBtn.setText("Delete Invoice");
        DeleteInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteInvoiceBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Invoice Date");

        jLabel2.setText("Invoice Total");

        jLabel3.setText("Customer Name");

        jLabel4.setText("Invoice Number");

        AllLinesTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(AllLinesTbl);

        SaveLineBtn.setText("Create Item");
        SaveLineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveLineBtnActionPerformed(evt);
            }
        });

        DeleteLineBtn.setText("Delete Item");
        DeleteLineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteLineBtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        LoadMenuBtn.setText("load file");
        LoadMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(LoadMenuBtn);

        SaveMenuBtn.setText("save file");
        SaveMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMenuBtnActionPerformed(evt);
            }
        });
        jMenu1.add(SaveMenuBtn);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(CreateNewInvoiceBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DeleteInvoiceBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(DateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(SaveLineBtn)
                                    .addGap(141, 141, 141)
                                    .addComponent(DeleteLineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(NumLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(DateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CustomerLabel)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(TotalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteInvoiceBtn)
                        .addComponent(CreateNewInvoiceBtn)
                        .addComponent(SaveLineBtn))
                    .addComponent(DeleteLineBtn))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadMenuBtnActionPerformed

    private void CreateNewInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewInvoiceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewInvoiceBtnActionPerformed

    private void DeleteLineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteLineBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteLineBtnActionPerformed

    private void SaveLineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveLineBtnActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_SaveLineBtnActionPerformed

    private void DeleteInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteInvoiceBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteInvoiceBtnActionPerformed

    private void SaveMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMenuBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveMenuBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AllHeadersTbl;
    private javax.swing.JTable AllLinesTbl;
    private javax.swing.JButton CreateNewInvoiceBtn;
    private javax.swing.JLabel CustomerLabel;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JButton DeleteInvoiceBtn;
    private javax.swing.JButton DeleteLineBtn;
    private javax.swing.JMenuItem LoadMenuBtn;
    private javax.swing.JLabel NumLabel;
    private javax.swing.JMenuItem SaveMenuBtn;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    private FileActions handler = new FileActions (this);
    private ArrayList<HeaderModel> arries;
    private ArrayList<LineModel> lstofLines;
    private InoviceHeaderTable invoiceheaderTable;
    public static SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    private ListOfListener selectionListener = new ListOfListener(this);

    

    public ArrayList<LineModel> getLinesArray() {
        return lstofLines;
    }

    public void setlstofLines(ArrayList<LineModel> Arr) {
        this.lstofLines = Arr;
    }
    
    public void setarries(ArrayList<HeaderModel> Arr) {
        this.arries = Arr;
    }

    public ArrayList<HeaderModel> getlstofLines() {
        return arries;
    }
    
    public HeaderModel getInvoices(int code) {
        for (HeaderModel inv : arries) {
            if (inv.getNum() == code) {
                return inv;
            }
        }
        return null;
    }

    public InoviceHeaderTable getTheheaderTable() {
        return invoiceheaderTable;
    }

    public void setTheheaderTable(InoviceHeaderTable tbl) {
        this.invoiceheaderTable = tbl;
    }
    
    public JTable gettheInvoicetbl() {
        return AllHeadersTbl;
    }

    public JTable getTheLinetbl() {
        return AllLinesTbl;
    }

    public JLabel getTheNameofCustLbl() {
        return CustomerLabel;
    }

    public JLabel getTheDateINsideTheLabel() {
        return DateLabel;
    }

    public JLabel getNumberOfTheInvoiceInsideLabel() {
        return NumLabel;
    }

    public JLabel getTheTotalOfTheInvoicelabel() {
        return TotalLabel;
    }

    public FileActions getTheSelectedActionHandler() {
        return handler;
    }

    
}

    
